module-template: ! 'module MODULE_NAME whereas

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
hidden-packages: ''
modules:
  World:
    filename: src/World.hs
  Json:
    filename: src/Json.hs
  Physics:
    filename: src/Physics.hs
  Test.Main:
    filename: src/Test/Main.hs
  Main:
    filename: src/Main.hs
  Simulation:
    filename: src/Simulation.hs
version: 1
extra-packages: ''
ghc-args: []
