extensions:
  OverloadedStrings: true
cabal-file: project.cabal
version: 1
module-template: ! 'module MODULE_NAME where

'
modules:
  Main(src/Main.hs):
    target-type: web
    filename: src/Main.hs
