extensions:
  OverloadedStrings: true
cabal-file: project.cabal
extra-packages: ''
version: 1
environment: ghc-7.4.2-stable-13.06
module-template: ! 'module MODULE_NAME where

'
ghc-args: []
modules:
  Main(src/Main.hs):
    filename: src/Main.hs
